---
# install_pip/tasks/linux.yml

- name: Install pip via the system package manager
  ansible.builtin.package:
    name: "{{ pip_package }}"
    state: present

- name: Remove EXTERNALLY-MANAGED
  ansible.builtin.file:
    path: /usr/lib/python3.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED
    state: absent
  when: not pip_externally_managed
